const ChainUtil = require('../chain-util');
const { INITIAL_BALANCE } = require('../config');

//Generates a wallet using.
class Wallet {
    constructor() {
        this.balance = INITIAL_BALANCE;
        this.keyPair = ChainUtil.genKeyPair();
        this.publicKey = this.keyPair.getPublic().encode('hex');
    }

    toString() {
        return `Wallet - 
            publicKey: ${this.publicKey.toString()}
            Balance  : ${this.balance}`
    }

    /**
     * Sign a transaction with one's private key (signature) generated by ec.
     * @param {*} dataHash - transaction hash before signature.
     * @returns the data signed.
     */
    sign(dataHash) {
        return this.keyPair.sign(dataHash);
    }
}

module.exports = Wallet;